export const Productos = [
    {
        id: '1',
        nombre: 'Catan',
        precio: 42000,
        img: 'Catan_base.jpg',
        alt: 'catan',
        categoria: 'Juego de mesa',
        empresa: 'Devir',
    },
    {
        id: '2',
        nombre: 'Bang!',
        precio: 25000,
        img: 'bang.jpg',
        alt: 'bang',
        categoria: 'Juego de mesa',
        empresa: 'Da Vinci Games',
    },
    {
        id: '3',
        nombre: 'Sushi Go! Party',
        precio: 18000,
        img: 'sushi-go-party.jpg',
        alt: 'sushi go party',
        categoria: 'Juego de mesa',
        empresa: 'Devir',
    },
    {
        id: '4',
        nombre: 'Cubo Rubik',
        precio: 9500,
        img: 'cubo-rubik.jpg',
        alt: 'cubo-rubik',
        categoria: 'Cubo Rubik',
        empresa: 'Hasbro',
    },
    {
        id: '5',
        nombre: 'Manual de Dungeons and Dragons',
        precio: 42600,
        img: 'manualDnD.jpg',
        alt: 'manual DnD',
        categoria: 'Juego de rol',
        empresa: 'Wizards of the Coast',
    },
    {
        id: '6',
        nombre: 'Set de dados',
        precio: 7500,
        img: 'setDados.jpg',
        alt: 'dados',
        categoria: 'Dados',
        empresa: 'T&G',
    },
    {
        id: '7',
        nombre: 'Manual de la llamada de Cthulhu',
        precio: 36000,
        img: 'manualCthulhu7ed.jpg',
        alt: 'manual Cthulhu 7e',
        categoria: 'Juego de rol',
        empresa: 'Edge Entertainment',
    },
    {
        id: '8',
        nombre: 'Alice ha desaparecido',
        precio: 9500,
        img: 'Alice-ha-desaparecido.jpg',
        alt: 'alice is missing',
        categoria: 'Juego de mesa',
        empresa: 'Devir',
    },
    {
        id: '9',
        nombre: 'Stone Age',
        precio: 38400,
        img: 'Stone_age.jpg',
        alt: 'stone age',
        categoria: 'Juego de mesa',
        empresa: 'Devir',
    },
];